services:
  app-restaurante:
    # image: app-restaurante
    # container_name: app-restaurante-container
    image: alejo224j/sistemarestaurante-api:latest # Usar la imagen de Docker Hub
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-restaurante-container
    ports:
      - "8080:8080"
    networks:
      - app-restaurante-network
    depends_on:
      # - postgres
      postgres:
        condition: service_healthy # esepera que postgres este bien para utilizar
    restart: unless-stopped
    volumes:
      - ./:/app # Monta el codigo actual
      # - m2-cache:/app/.m2  # Monta la cache de Maven
      - restaurante_uploads:/app/uploads #Volumen para imagenes
    working_dir: /app
    command: ./mvnw spring-boot:run # Comando para iniciar la aplicacion

  postgres:
    image: postgres
    container_name: postgres_restaurante
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5433:5432" # Para evitar conflictos con PostgreSQLS local
    networks:
      - app-restaurante-network
    volumes:
      - postgres-volume-restaurante:/var/lib/postgresql   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alejandro -d restaurante_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  app-restaurante-network:
volumes:
  postgres-volume-restaurante:
  m2-cache: #cache persistente de maven
  restaurante_uploads:
